In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import sklearn.linear_model


In [20]:
dtype_dict = {'bathrooms':float, 'waterfront':int, 'sqft_above':int, 'sqft_living15':float,
              'grade':int, 'yr_renovated':int, 'price':float, 'bedrooms':float, 'zipcode':str,
              'long':float, 'sqft_lot15':float, 'sqft_living':float, 'floors':str, 'condition':int,
              'lat':float, 'date':str, 'sqft_basement':int, 'yr_built':int, 'id':str, 'sqft_lot':int, 'view':int}

In [33]:
data_train = pd.read_csv('kc_house_train_data.csv', dtype=dtype_dict)
data_train.shape

(17384, 21)

In [34]:
data_test = pd.read_csv('kc_house_test_data.csv', dtype=dtype_dict)
data_test.shape

(4229, 21)

In [35]:
data_train.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0       3.0       1.00       1180.0   
1  6414100192  20141209T000000  538000.0       3.0       2.25       2570.0   
2  5631500400  20150225T000000  180000.0       2.0       1.00        770.0   
3  2487200875  20141209T000000  604000.0       4.0       3.00       1960.0   
4  1954400510  20150218T000000  510000.0       3.0       2.00       1680.0   

   sqft_lot floors  waterfront  view     ...      grade  sqft_above  \
0      5650      1           0     0     ...          7        1180   
1      7242      2           0     0     ...          7        2170   
2     10000      1           0     0     ...          6         770   
3      5000      1           0     0     ...          7        1050   
4      8080      1           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0         1340.0      5650.0  
1         1690.0      7639.0  
2         2720.0      8062.0  
3         1360.0      5000.0  
4         1800.0      7503.0  

[5 rows x 21 columns]

In [65]:
x_train = data_train['sqft_living'].values.reshape(-1,1)
y_train = data_train['price'].values.reshape(-1,1)
x_test = data_test['sqft_living'].values.reshape(-1,1)
y_test = data_test['price'].values.reshape(-1,1)

In [67]:
y_train

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [360000.],
       [400000.],
       [325000.]])

In [71]:
clf = sklearn.linear_model.LinearRegression()

In [72]:
clf.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [73]:
clf.coef_

array([[281.95883963]])

In [74]:
clf.intercept_

array([-47116.07907289])

## homework1:

In [93]:
clf.predict(2650)

array([[700074.84594751]])

- residual sum of squares: RSS  = sum( (y - y_predict)^2 )

- mean squared error:      MSE  = RSS/N

- root mean squared error: RMSE = sqrt(RSS/N)

## homework2:

In [107]:
#RSS on train
print(len(y_train))
len(y_train)*sklearn.metrics.mean_squared_error(y_train, clf.predict(x_train))

17384


1201918354177283.2

In [105]:
#RMSE
np.sqrt( sklearn.metrics.mean_squared_error(y_train, clf.predict(x_train)) )

262943.6135174753

In [108]:
# 检查模型
( x_train.dot(clf.coef_.T)+clf.intercept_ == clf.predict(x_train) ).mean()

1.0

## homework3:

In [114]:
3004.396*clf.coef_.T + clf.intercept_

array([[799999.93087715]])

In [112]:
(800000 - clf.intercept_)/clf.coef_

array([[3004.39624515]])

## homework4:

In [120]:
x_train = data_train['sqft_living'].values.reshape(-1,1)
y_train = data_train['price'].values.reshape(-1,1)
x_test = data_test['sqft_living'].values.reshape(-1,1)
y_test = data_test['price'].values.reshape(-1,1)

In [121]:
clf = sklearn.linear_model.LinearRegression()

In [122]:
clf.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [123]:
#RSS on test
print(len(y_test))
len(y_test)*sklearn.metrics.mean_squared_error(y_test, clf.predict(x_test))

4229


275402933617812.12

In [124]:
x2_train = data_train['bedrooms'].values.reshape(-1,1)
# y_train = data_train['price'].values.reshape(-1,1)
x2_test = data_test['bedrooms'].values.reshape(-1,1)
# y_test = data_test['price'].values.reshape(-1,1)

In [125]:
clf.fit(x2_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [126]:
#RSS on test
print(len(y_test))
len(y_test)*sklearn.metrics.mean_squared_error(y_test, clf.predict(x_test))

4229


3.5285983689210764e+20