In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import sklearn.linear_model


In [4]:
data_train = pd.read_csv('kc_house_train_data.csv')
data_test = pd.read_csv('kc_house_test_data.csv')
data_train.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [5]:
x_train = data_train['sqft_living'].values.reshape(-1,1)
y_train = data_train['price'].values.reshape(-1,1)
x_test = data_test['sqft_living'].values.reshape(-1,1)
y_test = data_test['price'].values.reshape(-1,1)

In [4]:
clf = sklearn.linear_model.LinearRegression()
clf.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
print(clf.intercept_)
print(clf.coef_)

[-47116.07907289]
[[281.95883963]]


In [6]:
clf.predict(x_test)

array([[356085.0615985 ],
       [784662.49783662],
       [435033.53669499],
       ...,
       [663420.19679557],
       [604208.8404732 ],
       [240481.93735006]])

In [7]:
sklearn.metrics.mean_squared_error(y_test, clf.predict(x_test))

65122471888.81819

In [8]:
x2_train = data_train[['sqft_living','sqft_living15']].values.reshape(-1,2)
# y_train = data_train['price'].values.reshape(-1,1)
x2_test = data_test[['sqft_living','sqft_living15']].values.reshape(-1,2)
# y_test = data_test['price'].values.reshape(-1,1)

In [9]:
x2_train.shape

(17384, 2)

In [10]:
clf2 = sklearn.linear_model.LinearRegression()
clf2.fit(x2_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
print(clf2.intercept_)
print(clf2.coef_)

[-100262.17515853]
[[245.18871442  65.27158522]]


In [12]:
clf2.predict(x2_test)

array([[366541.10816718],
       [762725.72477249],
       [386240.25928765],
       ...,
       [682097.7799554 ],
       [585570.75612155],
       [216407.33048282]])

In [13]:
y_test

array([[310000.],
       [650000.],
       [233000.],
       ...,
       [610685.],
       [400000.],
       [402101.]])

In [14]:
sklearn.metrics.mean_squared_error(y_test, clf2.predict(x2_test))

63908832943.749245

# This homework must hand with numpy !!!

In [6]:
print(data_train.index)
print(data_test.columns)
print(data_train.shape)
print(data_test.shape)
data_train.head()

RangeIndex(start=0, stop=17384, step=1)
Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')
(17384, 21)
(4229, 21)


id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view     ...      grade  sqft_above  \
0      5650     1.0           0     0     ...          7        1180   
1      7242     2.0           0     0     ...          7        2170   
2     10000     1.0           0     0     ...          6         770   
3      5000     1.0           0     0     ...          7        1050   
4      8080     1.0           0     0     ...          8        1680   

   sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
0              0      1955             0    98178  47.5112 -122.257   
1            400      1951          1991    98125  47.7210 -122.319   
2              0      1933             0    98028  47.7379 -122.233   
3            910      1965             0    98136  47.5208 -122.393   
4              0      1987             0    98074  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503  

[5 rows x 21 columns]

In [7]:
data_train[['price','bedrooms']].values

array([[2.219e+05, 3.000e+00],
       [5.380e+05, 3.000e+00],
       [1.800e+05, 2.000e+00],
       ...,
       [3.600e+05, 3.000e+00],
       [4.000e+05, 3.000e+00],
       [3.250e+05, 2.000e+00]])

In [8]:
def get_numpy_data(data_sframe, features_name, output_name):
    data_sframe['constant'] = 1 # add a constant column to an SFrame
    features_matrix = data_sframe[ (['constant'] + features_name) ].values
    output_array = data_sframe[output_name].values
    return(features_matrix, output_array)

In [9]:
def predict_outcome(feature_matrix, weights):
    predictions = feature_matrix.dot(weights)
    return(predictions)

In [10]:
def feature_derivative(errors, feature):
    derivative = (-2)*np.sum(errors * feature)
    return(derivative)

In [31]:
def regression_gradient_descent(feature_matrix, y_true, initial_weights, step_size, tolerance):
    converged = False
    weights = np.array(initial_weights)
    while not converged:
#     for ii in range(10):
        # compute the predictions based on feature_matrix and weights:
        # compute the errors as predictions - output:
#         errors = predict_outcome(feature_matrix, weights) - y_true 
        # !!! 就是这个地方害的
        errors = -predict_outcome(feature_matrix, weights) + y_true 
        # 本来应该是 y - y_predict 的，这样才对应 w = w - alpha*grad
        gradient_sum_squares = 0 # initialize the gradient
        # while not converged, update each weight individually:
        for i in range(len(weights)):
            # Recall that feature_matrix[:, i] is the feature column associated with weights[i]
            # compute the derivative for weight[i]:
            derivative = feature_derivative(errors, feature_matrix[:, i])
            # add the squared derivative to the gradient magnitude
            gradient_sum_squares += derivative**2
            # update the weight based on step size and derivative:
            weights[i] = weights[i] - step_size*derivative
        rss = len(y_true) * sklearn.metrics.mean_squared_error(y_true, predict_outcome(feature_matrix, weights))
        print(rss)
        gradient_magnitude = np.sqrt(gradient_sum_squares)
        print('weights[i]:',weights[i], ' derivative:', derivative, ' :gradient_magnitude', gradient_magnitude)
        if gradient_magnitude < tolerance:
            converged = True
    return(weights)

## homework1,2:

In [18]:
np.array([-47000., 1.])

array([-4.7e+04,  1.0e+00])

In [27]:
simple_features_name = ['sqft_living']
my_output_name= 'price'
(simple_feature_matrix, y_true) = get_numpy_data(data_train, simple_features_name, my_output_name)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

In [28]:
y_true

array([221900., 538000., 180000., ..., 360000., 400000., 325000.])

In [29]:
weights = regression_gradient_descent(simple_feature_matrix, y_true, initial_weights, step_size, tolerance)
weights

1680732633349715.2
weights[i]: 354.860686922526  derivative: -50551526703218.0  :gradient_magnitude 50551530784973.43
1234207738742912.0
weights[i]: 262.9685371605816  derivative: 13127449965992.057  :gradient_magnitude 13127451026296.443
1204095858980868.8
weights[i]: 286.8315078182051  derivative: -3408995808231.932  :gradient_magnitude 3408996083241.06
1202065232438527.0
weights[i]: 280.6346632584699  derivative: 885263508533.6006  :gradient_magnitude 885263580285.0402
1201928294984368.8
weights[i]: 282.2438879907589  derivative: -229889247469.85522  :gradient_magnitude 229889265767.8969
1201919060461936.2
weights[i]: 281.82599720848896  derivative: 59698683181.42047  :gradient_magnitude 59698688272.160736
1201918437722121.0
weights[i]: 281.9345169864691  derivative: -15502825425.727875  :gradient_magnitude 15502826425.342974
1201918395726998.2
weights[i]: 281.9063360801751  derivative: 4025843756.279846  :gradient_magnitude 4025844402.3531156
1201918392895010.0
weights[i]: 281.9136

array([-46999.88757389,    281.91214576])

In [176]:
(x_test, y_test) = get_numpy_data(data_test, simple_features_name, my_output_name)

In [177]:
predict_outcome(x_test, weights)

array([356134.443255  , 784640.86440132, 435069.83662406, ...,
       663418.65315598, 604217.10812919, 240550.47439317])

In [178]:
len(y_test) * sklearn.metrics.mean_squared_error(y_test, predict_outcome(x_test, weights))

275400044902128.3

In [179]:
y_test

array([310000., 650000., 233000., ..., 610685., 400000., 402101.])

## homework3,4:

In [180]:
model_features_name = ['sqft_living', 'sqft_living15']
my_output_name = 'price'
(feature_matrix, y_true) = get_numpy_data(data_train, model_features,my_output)
initial_weights = np.array([-100000., 1., 1.])
step_size = 4e-12
tolerance = 1e9

In [181]:
weights = regression_gradient_descent(feature_matrix, y_true, initial_weights, step_size, tolerance)
weights

weights[i]: 196.92903734403998  derivative: 48982259336010.0  :gradient_magnitude 73072020556001.0
weights[i]: 133.50564930194122  derivative: -15855847010524.693  :gradient_magnitude 22673220967534.742
weights[i]: 150.58566314222344  derivative: 4270003460070.5547  :gradient_magnitude 7060794583490.456
weights[i]: 142.75832408202035  derivative: -1956834765050.769  :gradient_magnitude 2275682396587.625
weights[i]: 142.71624194693015  derivative: -10520533772.54712  :gradient_magnitude 928984110636.1498
weights[i]: 140.31809341312388  derivative: -599537133451.5697  :gradient_magnitude 656307431862.795
weights[i]: 138.70790836436453  derivative: -402546262189.83795  :gradient_magnitude 610615358663.3832
weights[i]: 136.909181048812  derivative: -449681828888.1298  :gradient_magnitude 593078772020.3286
weights[i]: 135.22345812622052  derivative: -421430730647.8709  :gradient_magnitude 578705926685.8693
weights[i]: 133.55591855120844  derivative: -416884893753.0187  :gradient_magnitude 5

array([-9.99999688e+04,  2.45072603e+02,  6.52795267e+01])

In [182]:
(x_test, y_test) = get_numpy_data(data_test, model_features_name, my_output_name)

In [183]:
predict_outcome(x_test, weights)

array([366651.41162949, 762662.39850726, 386312.09557541, ...,
       682087.39916306, 585579.27901327, 216559.20391786])

In [184]:
len(y_test) * sklearn.metrics.mean_squared_error(y_test, predict_outcome(x_test, weights))

270263443629803.56

**key: 281.9, 356134.4, 366651.4, model1, model2**