In [604]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [605]:
people = pd.read_csv('people_wiki.csv')

In [606]:
people.head()

URI                 name  \
0        <http://dbpedia.org/resource/Digby_Morrell>        Digby Morrell   
1       <http://dbpedia.org/resource/Alfred_J._Lewy>       Alfred J. Lewy   
2        <http://dbpedia.org/resource/Harpdog_Brown>        Harpdog Brown   
3  <http://dbpedia.org/resource/Franz_Rottensteiner>  Franz Rottensteiner   
4               <http://dbpedia.org/resource/G-Enka>               G-Enka   

                                                text  
0  digby morrell born 10 october 1979 is a former...  
1  alfred j lewy aka sandy lewy graduated from un...  
2  harpdog brown is a singer and harmonica player...  
3  franz rottensteiner born in waidmannsfeld lowe...  
4  henry krvits born 30 december 1974 in tallinn ...

In [607]:
obama = people[people['name'] == 'Barack Obama']

In [608]:
obama

URI          name  \
35817  <http://dbpedia.org/resource/Barack_Obama>  Barack Obama   

                                                    text  
35817  barack hussein obama ii brk husen bm born augu...

In [609]:
obama.columns

Index(['URI', 'name', 'text'], dtype='object')

In [610]:
obama['text'].values

array(['barack hussein obama ii brk husen bm born august 4 1961 is the 44th and current president of the united states and the first african american to hold the office born in honolulu hawaii obama is a graduate of columbia university and harvard law school where he served as president of the harvard law review he was a community organizer in chicago before earning his law degree he worked as a civil rights attorney and taught constitutional law at the university of chicago law school from 1992 to 2004 he served three terms representing the 13th district in the illinois senate from 1997 to 2004 running unsuccessfully for the united states house of representatives in 2000in 2004 obama received national attention during his campaign to represent illinois in the united states senate with his victory in the march democratic party primary his keynote address at the democratic national convention in july and his election to the senate in november he began his presidential campaign in 2007 a

In [611]:
people['text'].shape

(59071,)

In [612]:
cout_vect = CountVectorizer()
people_couts = cout_vect.fit_transform(people['text'])
print(people_couts.shape)
people_couts[0].sum()

(59071, 548429)


247

In [613]:
# Both tf and tf–idf can be computed as follows:
tf_transformer = TfidfTransformer(use_idf=False).fit(people_couts)
people_tf = tf_transformer.transform(people_couts)
print(people_tf.shape)
people_tf.sum()

(59071, 548429)


472177.11741620075

In [614]:
print(people_tf[0].sum())
# 这个不应该是归一的吗？
np.linalg.norm(people_tf[0].toarray())
# 好像所有的，都是模长归一化，，奇怪。。。

6.506762616706824


1.0

In [615]:
tfidf_transformer = TfidfTransformer()
people_tfidf = tfidf_transformer.fit_transform(people_couts)
print(people_tfidf.shape)
people_tfidf[2256].sum()

(59071, 548429)


9.929876561137604

In [616]:
people_tfidf[0].sum()

8.40210889360581

In [617]:
people_tfidf.dtype

dtype('float64')

## homework:

In [341]:
# homework1:
# (the, in, and)
(people['name'] == 'Elton John').values.argmax()

19923

In [342]:
people.iloc[19923]

URI              <http://dbpedia.org/resource/Elton_John>
name                                           Elton John
text    sir elton hercules john cbe born reginald kenn...
Name: 19923, dtype: object

In [618]:
people_feature = cout_vect.get_feature_names()

In [619]:
max3 = people_couts[19923].toarray()
max3.sort()
max3

array([[ 0,  0,  0, ..., 15, 18, 27]], dtype=int64)

In [620]:
for i in [27,18,15]:
    print( (people_couts[19923].toarray() == i).argmax() )
    print( people_feature[(people_couts[19923].toarray() == i).argmax()] )

488148
the
251905
in
58906
and


In [621]:
# homework2:
# (furnish, elton, billboard)
max3 = people_tfidf[19923].toarray().copy()
max3.sort()
max3

array([[0.        , 0.        , 0.        , ..., 0.18895795, 0.19220734,
        0.24368352]])

In [622]:
max3[0,[-1,-2,-3]]

array([0.24368352, 0.19220734, 0.18895795])

In [623]:
for i in max3[0,[-1,-2,-3,-4,-5,-6,-7,-8,-9,-10]]:
#     print( (people_tfidf[19923].toarray() == i).argmax() )
    print( people_feature[(people_tfidf[19923].toarray() == i).argmax()] )

the
billboard
john
elton
furnish
in
and
songwriters
award
top


猜
3.
0.14
0.85
maybe:
0.3 to 0.49,no
0.5 to 0.69
0.9 to 1.0

4.
0.307
0.692
maybe:
0.1 to 0.29
0.7 to 0.89,yes
0.9 to 1

In [683]:
p1 = (people['name'] == 'Elton John').values.argmax()
p2 = (people['name'] == 'Victoria Beckham').values.argmax()
1 - people_tfidf[p2].toarray().reshape(-1,1).T.dot(people_tfidf[p1].toarray().reshape(-1,1))

array([[0.85192118]])

In [684]:
p1 = (people['name'] == 'Elton John').values.argmax()
p2 = (people['name'] == 'Paul McCartney').values.argmax()
1 - people_tfidf[p2].toarray().reshape(-1,1).T.dot(people_tfidf[p1].toarray().reshape(-1,1))

array([[0.69231325]])

In [631]:
# homework6,7,8,9:
# CR, RS, MF, DB
p1 = (people['name'] == 'Elton John').values.argmax()
p2 = (people['name'] == 'Victoria Beckham').values.argmax()

In [632]:
people_tf

<59071x548429 sparse matrix of type '<class 'numpy.float64'>'
	with 10244028 stored elements in Compressed Sparse Row format>

In [633]:
people_tf[p1]

<1x548429 sparse matrix of type '<class 'numpy.float64'>'
	with 252 stored elements in Compressed Sparse Row format>

In [649]:
# 只需改此句，就可以解答6,7,8,9四题
coslengthlist = np.dot(people_tfidf, people_tfidf[p2].T).toarray().reshape(1,-1)
whomax = coslengthlist.copy()
whomax.sort()

In [650]:
# people.couts没有归一化，所以以上code不能直接计算cos距离。
for i in range(5): print( np.linalg.norm(people_couts[i].toarray()) )

37.960505792204614
22.64950330581225
25.865034312755125
42.391036788453285
24.79919353527449


In [651]:
coslengthlist

array([[0.08898417, 0.03550114, 0.06473532, ..., 0.05070299, 0.07131342,
        0.06859877]])

In [652]:
whomax

array([[0.00000000e+00, 5.77882017e-04, 1.04079001e-03, ...,
        2.81578176e-01, 4.53523330e-01, 1.00000000e+00]])

In [653]:
for i in whomax[0,[-1,-2,-3]]:
    print((coslengthlist == i).argmax())
    print(people['name'][(coslengthlist == i).argmax()])

50411
Victoria Beckham
23386
David Beckham
17264
Mel B


## Sklearn: Working With Text Data
http://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html

In [67]:
categories = ['alt.atheism', 'soc.religion.christian',
              'comp.graphics', 'sci.med']

In [68]:
from sklearn.datasets import fetch_20newsgroups
twenty_train = fetch_20newsgroups(subset='train',
    categories=categories, shuffle=True, random_state=42)

In [92]:
print(dir(twenty_train))
twenty_train.description

['DESCR', 'data', 'description', 'filenames', 'target', 'target_names']


'the 20 newsgroups by date dataset'

In [110]:
print(twenty_train.target_names)
# For speed and space efficiency reasons scikit-learn loads the target attribute as an array of integers
# that corresponds to the index of the category name in the target_names list.
print(twenty_train.target[:10])
for i in range(10): print(twenty_train.target_names[twenty_train.target[i]])

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']
[1 1 3 3 3 3 3 2 2 2]
comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med


In [121]:
print(len(twenty_train.data))
twenty_train.data[0]

2257


'From: sd345@city.ac.uk (Michael Collier)\nSubject: Converting images to HP LaserJet III?\nNntp-Posting-Host: hampton\nOrganization: The City University\nLines: 14\n\nDoes anyone know of a good way (standard PC application/PD utility) to\nconvert tif/img/tga files into LaserJet III format.  We would also like to\ndo the same, converting to HPGL (HP plotter) files.\n\nPlease email any response.\n\nIs this the correct group?\n\nThanks in advance.  Michael.\n-- \nMichael Collier (Programmer)                 The Computer Unit,\nEmail: M.P.Collier@uk.ac.city                The City University,\nTel: 071 477-8000 x3769                      London,\nFax: 071 477-8565                            EC1V 0HB.\n'

In [122]:
print("\n".join(twenty_train.data[0].split("\n")[:3]))

From: sd345@city.ac.uk (Michael Collier)
Subject: Converting images to HP LaserJet III?
Nntp-Posting-Host: hampton


In [126]:
from sklearn.feature_extraction.text import CountVectorizer

In [184]:
cout_vect = CountVectorizer()
x_train_counts = cout_vect.fit_transform(twenty_train.data)
print(x_train_counts.shape)
x_train_counts.sum()

(2257, 35788)


691079

In [185]:
a = cout_vect.fit(twenty_train.data)
b = a.transform(twenty_train.data)
print(b.shape)
b.sum()

(2257, 35788)


691079

In [222]:
x_train_counts.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [227]:
cout_vect.get_feature_names().__len__()

35788

In [189]:
# Both tf and tf–idf can be computed as follows:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(x_train_counts)
x_train_tf = tf_transformer.transform(x_train_counts)
print(x_train_tf.shape)
x_train_tf[2256].sum()

(2257, 35788)


7.072540797572909

In the above example-code, we firstly use the fit(..) method to fit our estimator to the data and secondly the transform(..) method to transform our count-matrix to a tf-idf representation. These two steps can be combined to achieve the same end result faster by skipping redundant processing. This is done through using the fit_transform(..) method as shown below

In [190]:
tfidf_transformer = TfidfTransformer()
x_train_tfidf = tfidf_transformer.fit_transform(x_train_counts)
print(x_train_tfidf.shape)
x_train_tfidf[2256].sum()

(2257, 35788)


6.572084413828573